# Generated by Django 2.0.5 on 2018-06-24 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('year_end', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gross_income', models.FloatField(default=0)),
                ('eci', models.FloatField(default=0)),
                ('sub_f', models.FloatField(default=0)),
                ('rp_div', models.FloatField(default=0)),
                ('for_tax', models.FloatField(default=0)),
                ('qbai', models.FloatField(default=0)),
                ('int_exp', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subsidiary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=15)),
                ('ownership', models.FloatField(default=1.0)),
                ('ref', models.CharField(max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GILTI.Client')),
            ],
        ),
        migrations.AddField(
            model_name='financial',
            name='subsidiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GILTI.Subsidiary'),
        ),
    ]
