# Generated by Django 2.0.5 on 2018-06-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GILTI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financial',
            name='subsidiary',
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='eci',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='for_tax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='gross_income',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='int_exp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='qbai',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='rp_div',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='sub_f',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Financial',
        ),
    ]
