# Generated by Django 2.0.5 on 2018-07-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GILTI', '0003_auto_20180703_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tax_inc',
            field=models.FloatField(default=0),
        ),
    ]
